declare module 'britecharts';
declare module 'britecharts/dist/umd/bar.min';
declare module 'britecharts/dist/umd/colors.min';
declare module 'britecharts/dist/umd/donut.min';
declare module 'britecharts/dist/umd/heatmap.min';
declare module 'britecharts/dist/umd/legend.min';
declare module 'britecharts/dist/umd/line.min';
declare module 'britecharts/dist/umd/miniTooltip.min';
declare module 'britecharts/dist/umd/tooltip.min';
